//==============================================================
isbn13 TEXT UNIQUE,
"coverUrl" TEXT,
"priceCents" INTEGER NOT NULL DEFAULT 1500,
currency TEXT NOT NULL DEFAULT 'usd',
inventory INTEGER NOT NULL DEFAULT 100,
"publishedAt" TIMESTAMP,
"googleVolumeId" TEXT UNIQUE,
"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
"updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS "_AuthorToBook" (
"A" TEXT NOT NULL REFERENCES "Author"(id) ON DELETE CASCADE,
"B" TEXT NOT NULL REFERENCES "Book"(id) ON DELETE CASCADE,
PRIMARY KEY ("A","B")
);


CREATE TABLE IF NOT EXISTS "_CategoryToBook" (
"A" TEXT NOT NULL REFERENCES "Category"(id) ON DELETE CASCADE,
"B" TEXT NOT NULL REFERENCES "Book"(id) ON DELETE CASCADE,
PRIMARY KEY ("A","B")
);


CREATE TABLE IF NOT EXISTS "Cart" (
id TEXT PRIMARY KEY,
"userId" TEXT REFERENCES "User"(id) ON DELETE SET NULL,
"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
"updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS "CartItem" (
id TEXT PRIMARY KEY,
"cartId" TEXT NOT NULL REFERENCES "Cart"(id) ON DELETE CASCADE,
"bookId" TEXT NOT NULL REFERENCES "Book"(id) ON DELETE CASCADE,
qty INTEGER NOT NULL DEFAULT 1,
UNIQUE ("cartId","bookId")
);


CREATE TABLE IF NOT EXISTS "Order" (
id TEXT PRIMARY KEY,
"userId" TEXT REFERENCES "User"(id) ON DELETE SET NULL,
email TEXT NOT NULL,
"totalCents" INTEGER NOT NULL,
currency TEXT NOT NULL DEFAULT 'usd',
status TEXT NOT NULL DEFAULT 'PENDING',
"stripeSession" TEXT,
"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
"updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS "OrderItem" (
id TEXT PRIMARY KEY,
"orderId" TEXT NOT NULL REFERENCES "Order"(id) ON DELETE CASCADE,
"bookId" TEXT NOT NULL REFERENCES "Book"(id) ON DELETE RESTRICT,
qty INTEGER NOT NULL,
"unitCents" INTEGER NOT NULL
);


CREATE TABLE IF NOT EXISTS "Review" (
id TEXT PRIMARY KEY,
"userId" TEXT NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
"bookId" TEXT NOT NULL REFERENCES "Book"(id) ON DELETE CASCADE,
rating INTEGER NOT NULL,
content TEXT,
UNIQUE ("userId","bookId")
);


CREATE TABLE IF NOT EXISTS "Wishlist" (
id TEXT PRIMARY KEY,
"userId" TEXT NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
"bookId" TEXT NOT NULL REFERENCES "Book"(id) ON DELETE CASCADE,
UNIQUE ("userId","bookId")
);